## Recreating Mayer's Futura 13 ##

I tried to recreate Hansjörg Mayer's Futura 13.

(Instructor: Allison Parrish, Assembled with code help from Kevin Yeh)

In [1]:
## format from Allison's sample code
## modified for the width and height of Juptyer Notebook for ease

html_tmpl = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{title}</title>
    <style>
    html {{ min-height: 32em; overflow: hidden; }}
    </style>
</head>
<body style = "width: 547px; height: 496px">
{content}
</body>
</html>"""

from IPython.display import display, HTML
def show_html(src):
    return display(HTML(src), metadata=dict(isolated=True))

import random
import math

def mkdiv(content, **kwargs):
    if 'position' not in kwargs:
        kwargs['position'] = 'absolute'
    style_str = ' '.join([": ".join((k.replace('_', '-'), v))+";" for k, v in kwargs.items()])
    return f"<div style='{style_str}'>{content}</div>"



In [2]:
## Trying to use Perlin Noise

!pip install noise

In [3]:
## Code taken from https://medium.com/@yvanscher/playing-with-perlin-noise-generating-realistic-archipelagos-b59f004d8401


import numpy as np
from noise import pnoise2

def perlin_array(shape = (202, 202),
			scale=20, octaves = 6, 
			persistence = 0.5, 
			lacunarity = 2.0, 
			seed = None):

    if not seed:

        seed = np.random.randint(0, 100)
        print("seed was {}".format(seed))

    arr = np.zeros(shape)
    for i in range(shape[0]):
        for j in range(shape[1]):
            arr[i][j] = pnoise2(i / scale,
                                        j / scale,
                                        octaves=octaves,
                                        persistence=persistence,
                                        lacunarity=lacunarity,
                                        repeatx=1024,
                                        repeaty=1024,
                                        base=seed)
    max_arr = np.max(arr)
    min_arr = np.min(arr)
    norm_me = lambda x: (x-min_arr)/(max_arr - min_arr)
    norm_me = np.vectorize(norm_me)
    arr = norm_me(arr)
    return arr

In [4]:
## Norm distribution like bell curves

def norm(size=(202, 202)):
    normies = np.random.normal(loc = 0.5, scale = 0.2, size = size)

    # scale between 0 and 1
    max_arr = np.max(normies)
    min_arr = np.min(normies)
    norm_thing = lambda x: (x-min_arr)/(max_arr - min_arr)
    norm_thing = np.vectorize(norm_thing)
    normies = norm_thing(normies)
    return normies

In [10]:
## Defining the image

src = "—" ##counting grid on pic
blank = " "
current_index = 0
x_count = 25
y_count = 25
grid_size = 60
divs = []

shape_size = 200
noise_size = (shape_size + 2, shape_size + 2)

noise = perlin_array(shape=noise_size)
noise2 = perlin_array(shape=noise_size)

norms = norm(size=noise_size)
norms2 = norm(size=noise_size)
print("norms is ")
print(norms)

def noise_val(n, i, j):
    return n[i * int(shape_size / x_count)][j * int(shape_size / y_count)]

print("noise is ")
print(noise)

## THIS MAKES HORIZONTAL LINES ##

for i in range(x_count):
    for j in range(y_count):
        x_pos = (grid_size / x_count) * i
        y_pos = (grid_size / y_count) * j
#         degrees = 90* random.randint(1,4)
        degrees = 90 * 0
        if noise_val(noise, i, j) < 0.5: 
            if random.random() > (abs(12 - i) / 12):
                this_div = mkdiv(src,
                                top=f"{x_pos*7}px",
                                left=f"{y_pos*7}px",
                                font_family="Futura",
                                font_size="25px",
                                transform=f"rotate({degrees}deg)"
                                )

                divs.append(this_div)
                current_index += 1

## THIS MAKES VERTICAL LINES ##

            
            
for i in range(x_count-1):
    for j in range(y_count+1):
        x_pos = (grid_size / x_count) * i
        y_pos = (grid_size / y_count) * j
        degrees = 90 * 1
        if noise_val(norms2, i, j) < 0.5:
            if random.random() > (abs(12 - i) / 12):
                this_div = mkdiv(src,
                                top=f"{(x_pos*7)+11}px",
                                left=f"{(y_pos*7)-4}px",
                                font_family="Futura",
                                font_size="25px",
                                transform=f"rotate({degrees}deg)")
                divs.append(this_div)
                current_index = 0

        
html_src = html_tmpl.format(title="grid", content="".join(divs))
show_html(html_src)



seed was 61
seed was 64
norms is 
[[0.59177963 0.4493221  0.49564302 ... 0.45291562 0.49053989 0.46611448]
 [0.38803038 0.48079195 0.3482995  ... 0.62602434 0.32787324 0.32690856]
 [0.5648127  0.34368085 0.36579187 ... 0.54162464 0.60093889 0.71956768]
 ...
 [0.40691493 0.54258889 0.44695872 ... 0.6351551  0.52761666 0.6006871 ]
 [0.49827244 0.39184478 0.76926398 ... 0.47856017 0.48613014 0.45860921]
 [0.40877731 0.41397054 0.37781444 ... 0.20835438 0.15675631 0.49002679]]
noise is 
[[0.49025467 0.47072078 0.45463341 ... 0.47798304 0.49025467 0.51055254]
 [0.55717787 0.54334698 0.46510398 ... 0.57915477 0.57652295 0.60138148]
 [0.57645739 0.5912494  0.54964239 ... 0.62448906 0.64535396 0.6734442 ]
 ...
 [0.54566824 0.5634707  0.63162683 ... 0.52328868 0.57158922 0.58167537]
 [0.49025467 0.51030659 0.58938718 ... 0.45972684 0.49025467 0.51040218]
 [0.43996688 0.47516477 0.53477503 ... 0.40271954 0.42974108 0.46155288]]


In [7]:
open("test.html", "w").write(html_src)
!open test.html